# Generated by Django 3.0.5 on 2021-12-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_name', models.CharField(max_length=200)),
                ('Prod_price', models.FloatField()),
                ('Prod_desci', models.CharField(max_length=200)),
                ('Prod_image', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_price', models.FloatField()),
                ('Product_description', models.CharField(max_length=200)),
                ('Product_image', models.ImageField(blank=True, upload_to='product_img')),
            ],
        ),
        migrations.CreateModel(
            name='Productlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=200)),
            ],
        ),
    ]
